name: stop project
on: workflow_dispatch
jobs:
  stop_project:
    runs-on: ubuntu-22.04
    steps:
      - name: stop project
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          password: ${{ secrets.PASSWORD }}
          script: sudo systemctl stop ${GITHUB_REPOSITORY##*/}
