name: updata_restart.yml
on: push

jobs:
  updata_restart:
    runs-on: ubuntu-22.04
    steps:
      - name: update project and restart
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${GITHUB_REPOSITORY##*/} 
            git pull
            sudo systemctl stop ${GITHUB_REPOSITORY##*/} 
            sudo systemctl daemon-reload
            sudo systemctl start ${GITHUB_REPOSITORY##*/} 
